config/routes.rb
EmergencyApp::Application.routes.draw do
  resources :types

  resources :locations

  resources :categorizes

end

app/models/categorize.rb
class Categorize < ActiveRecord::Base
  attr_accessible :date, :description, :location_id, :type_id
  belongs_to :location
  belongs_to :type
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name, :radius
  has_many :categorizes
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name
  has_many :categorizes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categorizes_controller.rb
class CategorizesController < ApplicationController
  # GET /categorizes
  # GET /categorizes.json
  def index
    @categorizes = Categorize.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorizes }
    end
  end

  # GET /categorizes/1
  # GET /categorizes/1.json
  def show
    @categorize = Categorize.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorize }
    end
  end

  # GET /categorizes/new
  # GET /categorizes/new.json
  def new
    @categorize = Categorize.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorize }
    end
  end

  # GET /categorizes/1/edit
  def edit
    @categorize = Categorize.find(params[:id])
  end

  # POST /categorizes
  # POST /categorizes.json
  def create
    @categorize = Categorize.new(params[:categorize])

    respond_to do |format|
      if @categorize.save
        format.html { redirect_to @categorize, notice: 'Categorize was successfully created.' }
        format.json { render json: @categorize, status: :created, location: @categorize }
      else
        format.html { render action: "new" }
        format.json { render json: @categorize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorizes/1
  # PUT /categorizes/1.json
  def update
    @categorize = Categorize.find(params[:id])

    respond_to do |format|
      if @categorize.update_attributes(params[:categorize])
        format.html { redirect_to @categorize, notice: 'Categorize was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorizes/1
  # DELETE /categorizes/1.json
  def destroy
    @categorize = Categorize.find(params[:id])
    @categorize.destroy

    respond_to do |format|
      format.html { redirect_to categorizes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorizes_helper.rb
module CategorizesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/categorizes/_form.html.erb
<%= form_for(@categorize) do |f| %>
  <% if @categorize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorize.errors.count, "error") %> prohibited this categorize from being saved:</h2>

      <ul>
      <% @categorize.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorizes/edit.html.erb
<h1>Editing categorize</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorize %> |
<%= link_to 'Back', categorizes_path %>

app/views/categorizes/index.html.erb
<h1>Listing categorizes</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Type</th>
    <th>Description</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorizes.each do |categorize| %>
  <tr>
    <td><%= categorize.location %></td>
    <td><%= categorize.type %></td>
    <td><%= categorize.description %></td>
    <td><%= categorize.date %></td>
    <td><%= link_to 'Show', categorize %></td>
    <td><%= link_to 'Edit', edit_categorize_path(categorize) %></td>
    <td><%= link_to 'Destroy', categorize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categorize', new_categorize_path %>

app/views/categorizes/new.html.erb
<h1>New risk</h1>

<%= render 'form' %>

<%= link_to 'Back', categorizes_path %>

app/views/categorizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @categorize.location %>
</p>

<p>
  <b>Type:</b>
  <%= @categorize.type %>
</p>

<p>
  <b>Description:</b>
  <%= @categorize.description %>
</p>

<p>
  <b>Date:</b>
  <%= @categorize.date %>
</p>


<%= link_to 'Edit', edit_categorize_path(@categorize) %> |
<%= link_to 'Back', categorizes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmergencyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :radius %><br />
    <%= f.text_field :radius %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Radius</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.radius %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Radius:</b>
  <%= @location.radius %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>